In [1]:
import numpy as np
from node_feature_utils import parse_trajectory_data
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
from sklearn.linear_model import LinearRegression

In [6]:
file_path = "../point_cloud_data/6DoF-HMD-UserNavigationData-master/NavigationData/"
data_index = "H4"
file_name = f'{data_index}_nav.csv'
df = pd.read_csv(file_path+file_name)
# get the Participant 1-14 as test data
participant = ['P'+str(user_i).zfill(2)+'_V1' for user_i in range(1, 15)]
df = df[df['Participant'].isin(participant)]

In [7]:
df

,FrameNumber,HMDPX,HMDPY,HMDPZ,HMDRX,HMDRY,HMDRZ,Participant,Dataset,ViewFrame
0,1,0.0346,1.7656,-0.9146,13.7244,356.0449,346.6967,P01_V1,H4,1
1,2,0.0341,1.7666,-0.9166,13.6143,356.4417,351.0183,P01_V1,H4,2
2,3,0.0333,1.7668,-0.9189,13.6143,356.6888,354.1861,P01_V1,H4,3
3,4,0.0325,1.7664,-0.9209,13.3849,356.7282,355.7287,P01_V1,H4,4
4,5,0.0320,1.7664,-0.9220,13.3269,356.6877,356.4001,P01_V1,H4,5
...,...,...,...,...,...,...,...,...,...,...
4529,69,-0.0934,1.9562,-0.7376,21.9765,358.5581,2.5759,P14_V1,H4,197
4530,70,-0.0934,1.9564,-0.7381,21.9480,358.5598,2.6069,P14_V1,H4,198
4531,71,-0.0938,1.9562,-0.7396,22.0469,358.4823,2.6698,P14_V1,H4,199
4532,72,-0.0942,1.9558,-0.7401,22.2207,358.3978,2.7016,P14_V1,H4,200
4533,74,-0.0955,1.9541,-0.7411,23.0458,357.8340,2.7079,P14_V1,H4,201